{% set name = "cdcs" %}
{% set version = "0.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2d7d9e021b18c948cded5bd1baacb1a02df3f79bb708a651fd7b531ad900e933

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - pandas
    - requests
    - ipython
    - tqdm

test:
  requires:
    - python {{ python_min }}
  imports:
    - cdcs

about:
  home: https://github.com/usnistgov/pycdcs
  license: NIST-PD
  license_file: LICENSE.TXT
  summary: Python API client for performing REST calls to configurable data curation system (CDCS) databases
  description: |
    Python API client for performing REST calls to configurable data curation system (CDCS) databases
  doc_url: https://github.com/usnistgov/pycdcs
  dev_url: https://github.com/usnistgov/pycdcs

extra:
  recipe-maintainers:
    - lmhale99
