{% set name = "cdcs" %}
{% set version = "0.2.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ec478cd130b224ed766fb028698808b92ef433b6dd7cc87372d3dd910a8cce5d

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - uv_build
  run:
    - python >={{ python_min }}
    - pandas
    - requests
    - ipython
    - tqdm

test:
  requires:
    - python {{ python_min }}
  imports:
    - cdcs

about:
  home: https://github.com/usnistgov/pycdcs
  license: NIST-Software
  license_file: LICENSE.TXT
  summary: Python API client for performing REST calls to configurable data curation system (CDCS) databases
  description: |
    Python API client for performing REST calls to configurable data curation system (CDCS) databases
  doc_url: https://github.com/usnistgov/pycdcs
  dev_url: https://github.com/usnistgov/pycdcs

extra:
  recipe-maintainers:
    - lmhale99
