{% set name = "cdcs" %}
{% set version = "0.1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 21732226dc36c76a3b4b70df518df9491d8231d1ac01f6c78d79c602ae84d4d7

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy
    - pandas
    - requests

test:
  imports:
    - cdcs

about:
  home: https://github.com/usnistgov/pycdcs
  license: NIST-PD
  license_file: LICENSE.TXT
  summary: Python API client for performing REST calls to configurable data curation system (CDCS) databases
  description: |
    Python API client for performing REST calls to configurable data curation system (CDCS) databases
  doc_url: https://github.com/usnistgov/pycdcs
  dev_url: https://github.com/usnistgov/pycdcs

extra:
  recipe-maintainers:
    - lmhale99
